// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kvozwtbjchlqularcdxs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt2b3p3dGJqY2hscXVsYXJjZHhzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxODQwMzcsImV4cCI6MjA2Mjc2MDAzN30.3Aqk0GR4n1zR4XCfuOtK07dXU6In4BiJAIUNL2dHd10";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);